[package]
name = "cross-llvm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
target-lexicon = { workspace = true }
thiserror = { workspace = true }
which = { workspace = true }

[[bin]]
name = "cross-llvm"
