# NOTE(vadorovsky): Debian bookworm (stable) doesn't provide risv64 builds of
# libzstd-dev.[0]
#
# Debian trixie (testing) provides all riscv64 we need, but it doesn't provide
# `software-properties-common`, while stable versions and Debian sid (unstable)
# provide it.[1] Don't ask me why, let's just stick to sid. ¯\_(ツ)_/¯
#
# [0] https://packages.debian.org/search?keywords=libzstd-dev
# [1] https://packages.debian.org/search?keywords=software-properties-common
FROM docker.io/debian:sid

ENV PATH="/root/.cargo/bin:/usr/lib/llvm-18/bin:${PATH}"

# Even though we are using clang as a C compiler, we need the libgcc_s and
# libstdc++.
RUN dpkg --add-architecture riscv64 \
    && apt update \
    && apt install -y \
        build-essential \
        cmake \
        curl \
        gcc-riscv64-linux-gnu \
        g++-riscv64-linux-gnu \
        gnupg \
        libc6-dev-riscv64-cross \
        libzstd-dev \
        libzstd-dev:riscv64 \
        lsb-release \
        ninja-build \
        qemu-user \
        software-properties-common \
        wget \
        zlib1g-dev \
        zlib1g-dev:riscv64 \
    && wget https://apt.llvm.org/llvm.sh \
    && chmod +x llvm.sh \
    && ./llvm.sh 18 \
    && rm -f llvm.sh \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && rustup toolchain install stable --component rust-src \
    && rustup toolchain install nightly --component rust-src \
    && rustup target add aarch64-unknown-linux-gnu \
    && rustup +nightly target add aarch64-unknown-linux-gnu \
    && cargo install btfdump \
    && rm -rf /var/lib/apt/lists/*
